MLSTORIES = [ {"title" : "A Day at the Zoo",
               "nounCount" : 3,
               "verbCount" : 1,
               "ptverbCount" : 2,
               "adjectiveCount" : 4,
               "adverbCount" : 2,
               "pNounCount" : 0,
               "numCount" : 0,
               "propNounCount" : 0,
               "estadjectiveCount" : 0,
               "ingVerbCount" : 0,
               "fNameCount" : 0,
               "lAnimalCount" : 0,
               "sAnimalCount" : 0,
               "girlNameCount" : 0,
               "story" : "Today I went to the zoo. I saw a(n) *adjective* *noun* jumping up and down in its tree. He *ptverb* *adverb* through the large tunnel that led to its *adjective* *noun*. I got some peanuts and passed them through the cage to a gigantic gray *noun* towering above my head. Feeding that animal made me hungry. I went to get a *adjective* scoop of ice cream. It filled my stomach. Afterwards I had to *verb* *adverb* to catch our bus. When I got home I *ptverb* my mom for a *adjective* day at the zoo. "},
              {"title" : "The Fun Park!",
               "nounCount" : 1,
               "verbCount" : 0,
               "ptverbCount" : 2,
               "adjectiveCount" : 2,
               "adverbCount" : 2,
               "pNounCount" : 1,
               "numCount" : 1,
               "propNounCount" : 0,
               "estadjectiveCount" : 1,
               "ingVerbCount" : 0,
               "fNameCount" : 0,
               "lAnimalCount" : 0,
               "sAnimalCount" : 0,
               "girlNameCount" : 0,
               "story" : "Today, my fabulous camp group went to a(n) *adjective* amusement park. It was a fun park with lots of cool *pnoun* and enjoyable play structures. When we got there, my kind counselor shouted loudly, \"Everybody off the *noun*\". We all pushed out in a terrible hurry. My counselor handed out yellow tickets, and we scurried in. I was so excited! I couldn't figure out what exciting thing to do first. I saw a scary rollercoaster I really liked so, I  *adverb* ran over to get in the long line that had about *number* people in it. When I finally got on the roller coaster I was  *ptverb*. In fact I was so nervous my two knees were knocking together. This was the *estadj* ride I had ever been on! In about two minutes I heard the crank and grinding of the gears. That’s when the ride began! When I got to the bottom, I was a little  *ptverb* but I was proud of myself. The rest of the day went *adverb*. It was a(n) *adjective* day at the fun park."
               },
              {"title" : "At the Arcade",
               "nounCount" : 2,
               "verbCount" : 1,
               "ptverbCount" : 0,
               "adjectiveCount" : 0,
               "adverbCount" : 0,
               "pNounCount" : 4,
               "numCount" : 0,
               "propNounCount" : 0,
               "estadjectiveCount" : 0,
               "ingVerbCount": 1,
               "fNameCount" : 0,
               "lAnimalCount" : 0,
               "sAnimalCount" : 0,
               "girlNameCount" : 0,
               "story" : "When I go to the arcade with my *pnoun* there are lots of games to play. I spend lots of time there with my friends. In the game X-Men you can be different  *pnoun*. The point of the game is to *verb* every robot. You also need to save people. Then you can go to the next level.  In the game Star Wars you are Luke Skywalker and you try to destroy every *noun*. In a car racing/motorcycle racing game you need to beat every computerized vehicle that you are  *ingverb* against. There are a whole lot of other cool games. When you play some games you win  *pnoun* for certain scores. Once you're done you can cash in your tickets to get a big *noun*. You can save your  *pnoun* for another time. When I went to this arcade I didn't believe how much fun it would be. So far I have had a lot of fun every time I've been to this great arcade! "},
              {"title" : "The First Day of School",
               "nounCount" : 2,
               "verbCount" : 0,
               "ptverbCount" : 0,
               "adjectiveCount" : 3,
               "adverbCount" : 1,
               "pNounCount" : 2,
               "numCount" : 1,
               "propNounCount" : 2,
               "estadjectiveCount" : 0,
               "ingVerbCount": 1,
               "fNameCount" : 0,
               "lAnimalCount" : 0,
               "sAnimalCount" : 0,
               "girlNameCount" : 0,
               "story" : "One very nice morning near the end of summer, my mother woke me up at 4:00 A.M. and said, \"Wake up and smell the grass, sleepy head! Today is your first day of school and you can't be late.\" I groaned in my bed for twenty seconds, but eventually I got dressed. I wore a blue and white striped, long sleeve *noun* with a collar on it, a red tie, dark gray pants, white socks, black shoes, and a(n) *adjective* hat. In ten minutes I made lunch and ate my breakfast. *number* minutes later, the bus came. A few minutes later, I was at school. In school, I met two really *adjective* kids. All of us became friends very fast. That day we had Science, and luckily my friends and I were at the same *noun*. My friends' names are *propnoun* and *propnoun*. In Math we weren't together, and that really bugged me. We learned what *pnoun* were, and when to use them. At snack and recess, we played a game together. It was extremely fun. At P.E., we were *ingverb* off of the ropes onto  *pnoun*. I thought it was a very *adjective* idea. In swimming class, we needed to swim extremely *adverb*, or else we would have to swim longer. Before I knew it, school was over. I grabbed all my belongings and put them into my backpack. In two minutes, the bus came. As I stepped into the bus I shouted, \"Goodbye, adios amigos, and shalom,\" to my friends. Then I went into the bus. In a flash, I was back home. This day was an extremely exciting day! "
               },
              {"title" : "In the Jungle",
               "nounCount" : 4,
               "verbCount" : 4,
               "ptverbCount" : 0,
               "adjectiveCount" : 7,
               "adverbCount" : 0,
               "pNounCount" : 0,
               "numCount" : 0,
               "propNounCount" : 0,
               "estadjectiveCount" : 0,
               "ingVerbCount": 0,
               "fNameCount" : 0,
               "lAnimalCount" : 0,
               "sAnimalCount" : 0,
               "girlNameCount" : 0,
               "story" : "I walk through the color jungle. I take out my *adjective* canteen. There's a *adjective* parrot with a *adjective* *noun* in his mouth right there in front of me in the *adjective* trees! I gaze at his *adjective* *noun*. A sudden sound awakes me from my daydream! A panther’s *verb* in front of my head! I *verb* his *adjective* breath. I remember I have a packet of *noun* that makes go into a deep slumber! I *verb*it away from me in front of the *noun*. Yes he's eating it! I *verb* away through the *adjective* jungle. I meet my parents at the tent. Phew! It’s been an exciting day in the jungle. "
               },
              {"title" : "Make Me A Video Game",
               "nounCount" : 0,
               "verbCount" : 0,
               "ptverbCount" : 1,
               "adjectiveCount" : 6,
               "adverbCount" : 0,
               "pNounCount" : 5,
               "numCount" : 3,
               "propNounCount" : 0,
               "estadjectiveCount" : 0,
               "ingVerbCount": 0,
               "fNameCount" : 3,
               "lAnimalCount" : 1,
               "sAnimalCount" : 1,
               "girlNameCount" : 1,
               "story" : "I, the *adjective* and *adjective* *fname* has *ptverb* *fname*'s *adjective* sister and plans to steal her *adjective* *pnoun*! What are a *lanimal* and backpacking *sanimal* to do? Before you can help *girlname*, you'll have to collect the *adjective* *pnoun* and *adjective* *pnoun* that open up the *number* worlds connected to a *fname* lair. There are *number* *pnoun* and *number* *pnoun* in the game, along with hundreds of other goodies for you to find."
               },
              {"title" : "The Monkey King",
               "nounCount" : 1,
               "verbCount" : 1,
               "ptverbCount" : 0,
               "adjectiveCount" : 1,
               "adverbCount" : 1,
               "pNounCount" : 0,
               "numCount" : 0,
               "propNounCount" : 0,
               "estadjectiveCount" : 0,
               "ingVerbCount": 0,
               "fNameCount" : 0,
               "lAnimalCount" : 0,
               "sAnimalCount" : 0,
               "girlNameCount" : 0,
               "story" : ""
               }
    ]